services:
  postgres:
    image: postgres:16
    container_name: cavent-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cavent
      POSTGRES_PASSWORD: cavent
      POSTGRES_DB: cavent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: redis:latest
    container_name: cavent-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  network:
    driver: bridge
