services:
  postgres:
    image: postgres:16
    container_name: cavent-postgres
    environment:
      POSTGRES_USER: cavent
      POSTGRES_PASSWORD: cavent
      POSTGRES_DB: cavent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: redis:latest
    container_name: cavent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cavent-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - network

  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: cavent-asynqmon
    command: ["--redis-addr=redis:6379", "--redis-db=1"]
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8081:8080"
    networks:
      - network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  network:
    driver: bridge
