services:
  postgres:
    image: postgres:16
    container_name: caveant-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cavent
      POSTGRES_PASSWORD: cavent
      POSTGRES_DB: cavent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
